### ISSUE TITLE
docs: update predeploy section with latest predeploys

### ISSUE THREAD

**Issue by emilianobonassi** [ethereum-optimism/specs#129]
Seems https://specs.optimism.io/protocol/predeploys.html does not contain all predeploys like Multicall3 and SafeSingletonFactory

https://github.com/ethereum-optimism/optimism/blob/develop/op-bindings/predeploys/addresses.go#L9-L38

**Comment by mds1** [comment]
These are known as [preinstalls](https://specs.optimism.io/protocol/preinstalls.html) so are in a separate section. We use this terminology to differentiate from standard OP Stack predeploys because preinstalls are written by third party developers and consequently we can't assume they have the same security guarantees. 

However:
- The create2deployer is in the predeploys section, but should be moved to preinstalls
- The preinstalls are missing an entry from the specification overview (screenshot below)

So I'll leave this issue open to account for those

<img width="328" alt="image" src="https://github.com/ethereum-optimism/specs/assets/17163988/55f8f798-7e81-4602-9d3d-ab3b5d9c5c68">

**Comment by emilianobonassi** [comment]
thanks @mds1 - closing
