### ISSUE TITLE
Hardfork Names

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/specs#174]
We have ran out of known hardfork names and it is blocking coordination and progress on new features. This issue exists to track a proposal on the next set of names. The theme is geology related and alphabetical so its obvious the order that they came in. The words should not be copyrightable to ensure that we cannot be sued in some way for using them. Picking names opens up a huge door for bikeshedding, opening an issue rather than a pull request as there is an [open PR](https://github.com/ethereum-optimism/specs/pull/145) that restructures the repo and it would clobber the diff. We should open a PR as soon as we can with the boilerplate for these so that we can easily target specific network upgrades with specs.

- Granite
- Holocene
- Igneous
- Jovian
- Krypton
- Lava
- Monsoon
- Nebula
- Orogeny
- Permafrost

**Comment by mds1** [comment]
> The Holocene is the name given to the last 11,700 years* of the Earth's history — the time since the end of the last major glacial epoch, or "ice age."

> A giant planet, sometimes referred to as a jovian planet, is a diverse type of planet much larger than Earth. Giant planets are usually primarily composed of low-boiling point materials (volatiles), rather than rock or other solid matter, but massive solid planets can also exist. 

> Orogeny is a mountain-building process that takes place at a convergent plate margin when plate motion compresses the margin. An orogenic belt or orogen develops as the compressed plate crumples and is uplifted to form one or more mountain ranges. 

Love this, I am learning so much

**Comment by sebastianst** [comment]
Happy to use almost all of these new names, they sound mostly cooler than the old names in Github. Since we didn't use any of the higher fork names in any code or specs yet, I don't see a problem with changing these at the current moment.

@protolambda mentioned 3 name clashes with existing projects, maybe we just use the old names for these (Krypton, Lava, Nebula).

For reference, this is what we agreed to last year
<img width="529" alt="image" src="https://github.com/ethereum-optimism/specs/assets/2607372/6b1f2123-87bf-40f7-b8a8-3ad723fb2d9a">

When these names are settled, they should be updated at https://github.com/orgs/ethereum-optimism/projects/47/settings/fields/57300142

**Comment by tynes** [comment]
@sebastianst I updated the tracker to match the names in PR #187 - thanks for helping to land this to the specs repo!

**Comment by sebastianst** [comment]
Thanks @tynes approved the specs pr.

**Comment by protolambda** [comment]
Hardfork names as proposed in #187 look good to me. Thanks for putting this together.
